language: node_js
node_js:
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"
  
branches:
  only:
    - master
    
before_script:
  - npm install -g mocha

script:
  - npm -d install
  - npm test
  
after_success:
  - git clone git@github.com:andrewbeng89/mitb_travis-ci.git
  - cd mitb_travis-ci
  - git branch -a
  - git checkout gh-pages
  - ls
  - git checkout master -- public
  - git add -A .
  - git config --global user.email "andrew.beng.2010@sis.smu.edu.sg"
  - git config --global user.name "andrewbeng89"
  - git commit -m "drone.io update"
  - git status
  - echo -e "Host heroku.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - git push origin gh-pages